// frontend/src/nodes/MixNode.tsx
import { Handle, Position } from "@xyflow/react";
import type { NodeProps } from "@xyflow/react";
import { IrPreview } from "../components/IrPreview";
import { useFlowStore } from "../flow/store";
import type { MixFlowNode } from "../flow/types";
import { cn } from "../lib/utils";
import { NodeShell, NodeStatus } from "./NodeShell";
import { OutPorts } from "./PortHandles";

/* «Микс» — run-based. Входы динамические из data.inputs (зеркало renderMixInputs,
 * nodes.js:781-813): handle kind "ir" на каждый вход, слайдер веса 0..100,
 * «+ вход» (макс. 4) и «✕» со снятием проводов удалённого входа.
 * POST /api/mix с нормированными весами (payload — зеркало runMix, nodes.js:815-836). */
export function MixNode({ id, data, selected }: NodeProps<MixFlowNode>) {
  const setNodeData = useFlowStore((s) => s.setNodeData);
  const addMixInput = useFlowStore((s) => s.addMixInput);
  const removeMixInput = useFlowStore((s) => s.removeMixInput);
  const runNode = useFlowStore((s) => s.runNode);
  const busy = useFlowStore((s) => !!s.busy[Number(id)]);
  return (
    <NodeShell id={id} type="mix" selected={selected}>
      {data.inputs.map((name) => {
        const weight = data.weights[name] ?? 50;
        return (
          <div key={name} className="mix-row port-row in" data-port={name} data-kind="ir">
            <Handle
              id={name}
              type="target"
              position={Position.Left}
              className={cn("port-dot port-ir", "pp-in-" + name)}
            />
            <span className="cap">{name}</span>
            <input
              type="range"
              min={0}
              max={100}
              value={weight}
              className="nodrag"
              onChange={(e) =>
                setNodeData(Number(id), {
                  weights: { ...data.weights, [name]: Number(e.target.value) },
                })
              }
            />
            <span className="wv">{weight}</span>
            <button className="mx nodrag" title="Убрать вход" onClick={() => removeMixInput(Number(id), name)}>
              ✕
            </button>
          </div>
        );
      })}
      <div className="ctl-row">
        <button className="btn-node small f-add-in nodrag" onClick={() => addMixInput(Number(id))}>
          + вход
        </button>
        <button
          className="btn-node primary small f-run nodrag"
          style={{ marginLeft: "auto" }}
          disabled={busy}
          onClick={() => runNode(Number(id))}
        >
          {busy ? <span className="spinner" /> : null} Смешать по весам
        </button>
      </div>
      <IrPreview
        className="f-preview"
        ir={data.ir}
        height={160}
        empty="Подключите ≥2 IR-входа и нажмите «Смешать»"
      />
      <NodeStatus id={id} />
      <OutPorts type="mix" data={data} />
    </NodeShell>
  );
}

// frontend/src/nodes/MixNode.svelte
<script lang="ts">
  import { Handle, Position } from "@xyflow/svelte";
  import type { NodeProps } from "@xyflow/svelte";
  import IrPreview from "../components/IrPreview.svelte";
  import { flow } from "../flow/state";
  import type { MixFlowNode } from "../flow/types";
  import { cn } from "../lib/utils";
  import NodeShell from "./NodeShell.svelte";
  import NodeStatus from "./NodeStatus.svelte";
  import OutPorts from "./OutPorts.svelte";

  /* «Микс» — run-based. Входы динамические из data.inputs (зеркало renderMixInputs,
   * nodes.js:781-813): handle kind "ir" на каждый вход, слайдер веса 0..100,
   * «+ вход» (макс. 4) и «✕» со снятием проводов удалённого входа.
   * POST /api/mix с нормированными весами (payload — зеркало runMix, nodes.js:815-836). */
  let { id, data, selected }: NodeProps<MixFlowNode> = $props();

  let busy = $derived(!!$flow.busy[Number(id)]);
</script>

<NodeShell {id} type="mix" {selected}>
  {#each data.inputs as name (name)}
    {@const weight = data.weights[name] ?? 50}
    <div class="mix-row port-row in" data-port={name} data-kind="ir">
      <Handle id={name} type="target" position={Position.Left} class={cn("port-dot port-ir", "pp-in-" + name)} />
      <span class="cap">{name}</span>
      <input
        type="range"
        min={0}
        max={100}
        value={weight}
        class="nodrag"
        oninput={(e) =>
          $flow.setNodeData(Number(id), {
            weights: { ...data.weights, [name]: Number(e.currentTarget.value) },
          })
        }
      />
      <span class="wv">{weight}</span>
      <button class="mx nodrag" title="Убрать вход" onclick={() => $flow.removeMixInput(Number(id), name)}>✕</button>
    </div>
  {/each}
  <div class="ctl-row">
    <button class="btn-node small f-add-in nodrag" onclick={() => $flow.addMixInput(Number(id))}>+ вход</button>
    <button
      class="btn-node primary small f-run nodrag"
      style="margin-left: auto"
      disabled={busy}
      onclick={() => $flow.runNode(Number(id))}
    >
      {#if busy}<span class="spinner"></span>{/if} Смешать по весам
    </button>
  </div>
  <IrPreview class="f-preview" ir={data.ir} height={160} empty="Подключите ≥2 IR-входа и нажмите «Смешать»" />
  <NodeStatus {id} />
  <OutPorts type="mix" {data} />
</NodeShell>
