// frontend/src/nodes/NodeShell.tsx
import type { ReactNode } from "react";
import { NODE_DEFS } from "../flow/ports";
import { useFlowStore } from "../flow/store";
import type { NodeType } from "../flow/types";
import { cn } from "../lib/utils";

/* Общий каркас ноды: шапка (иконка, название, ✕) и тело.
 * Зеркало .node-head/.node-body legacy; классы n-<type>, f-* и data-id
 * сохранены для тестов (dataset.id на .node — контракт buildNodeDom legacy). */
export function NodeShell({
  id,
  type,
  selected,
  children,
}: {
  id: string;
  type: NodeType;
  selected?: boolean;
  children: ReactNode;
}) {
  const def = NODE_DEFS[type];
  const deleteNode = useFlowStore((s) => s.deleteNode);
  return (
    <div
      className={cn("fnode node", "n-" + type, selected && "selected")}
      data-id={id}
      style={{ width: def.w }}
    >
      <div className="node-head">
        <span className="n-icon">{def.icon}</span>
        <span className="n-title">{def.title}</span>
        <button className="n-x nodrag" title="Удалить ноду (Del)" onClick={() => deleteNode(Number(id))}>
          ✕
        </button>
      </div>
      <div className="node-body">{children}</div>
    </div>
  );
}

/* Статусная строка ноды — зеркало .n-status (runtime, в сейв не попадает) */
export function NodeStatus({ id }: { id: string }) {
  const status = useFlowStore((s) => s.statuses[Number(id)]);
  return <div className={cn("n-status", status?.kind)}>{status?.text || ""}</div>;
}

// frontend/src/nodes/NodeShell.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { NODE_DEFS } from "../flow/ports";
  import { flow } from "../flow/state";
  import type { NodeType } from "../flow/types";
  import { cn } from "../lib/utils";

  /* Общий каркас ноды: шапка (иконка, название, ✕) и тело.
   * Зеркало .node-head/.node-body legacy; классы n-<type>, f-* и data-id
   * сохранены для тестов (dataset.id на .node — контракт buildNodeDom legacy). */
  let {
    id,
    type,
    selected = false,
    children,
  }: {
    id: string;
    type: NodeType;
    selected?: boolean;
    children?: Snippet;
  } = $props();

  let def = $derived(NODE_DEFS[type]);
</script>

<div class={cn("fnode node", "n-" + type, selected && "selected")} data-id={id} style="width: {def.w}px">
  <div class="node-head">
    <span class="n-icon">{def.icon}</span>
    <span class="n-title">{def.title}</span>
    <button class="n-x nodrag" title="Удалить ноду (Del)" onclick={() => $flow.deleteNode(Number(id))}>✕</button>
  </div>
  <div class="node-body">{@render children?.()}</div>
</div>
