// frontend/src/nodes/PageBridgeNode.svelte
<script lang="ts">
  import type { NodeProps } from "@xyflow/svelte";
  import { flow } from "../flow/state";
  import type { PageBridgeFlowNode } from "../flow/types";
  import NodeShell from "./NodeShell.svelte";
  import NodeStatus from "./NodeStatus.svelte";
  import InPorts from "./InPorts.svelte";
  import OutPorts from "./OutPorts.svelte";

  let { id, data, selected }: NodeProps<PageBridgeFlowNode> = $props();

  let hasComponent = $derived(Boolean(data.ir));
</script>

<NodeShell {id} type="pagebridge" {selected}>
  <InPorts type="pagebridge" {data} />
  <div class="bridge-mode nodrag">
    <button class={data.mode === "send" ? "active" : ""} onclick={() => $flow.setNodeData(Number(id), { mode: "send" })}>
      Send
    </button>
    <button class={data.mode === "receive" ? "active" : ""} onclick={() => $flow.setNodeData(Number(id), { mode: "receive" })}>
      Receive
    </button>
  </div>
  <label class="field">
    <span>Channel</span>
    <input
      class="nodrag"
      value={data.channel}
      oninput={(e) => $flow.setNodeData(Number(id), { channel: e.currentTarget.value })}
      onblur={() => $flow.runNode(Number(id))}
      placeholder="shared-component"
    />
  </label>
  <button class="btn-node primary small f-run nodrag" onclick={() => $flow.runNode(Number(id))}>
    {data.mode === "send" ? "Передать" : "Получить"}
  </button>
  <div class="bridge-chip">{hasComponent ? "component ready" : "empty channel"}</div>
  <NodeStatus {id} />
  <OutPorts type="pagebridge" {data} />
</NodeShell>

// frontend/src/nodes/PageBridgeNode.tsx
import type { NodeProps } from "@xyflow/react";
import { useFlowStore } from "../flow/store";
import type { PageBridgeFlowNode } from "../flow/types";
import { NodeShell, NodeStatus } from "./NodeShell";
import { InPorts, OutPorts } from "./PortHandles";

export function PageBridgeNode({ id, data, selected }: NodeProps<PageBridgeFlowNode>) {
  const setNodeData = useFlowStore((s) => s.setNodeData);
  const runNode = useFlowStore((s) => s.runNode);
  const hasComponent = Boolean(data.ir);

  return (
    <NodeShell id={id} type="pagebridge" selected={selected}>
      <InPorts type="pagebridge" data={data} />
      <div className="bridge-mode nodrag">
        <button
          className={data.mode === "send" ? "active" : ""}
          onClick={() => setNodeData(Number(id), { mode: "send" })}
        >
          Send
        </button>
        <button
          className={data.mode === "receive" ? "active" : ""}
          onClick={() => setNodeData(Number(id), { mode: "receive" })}
        >
          Receive
        </button>
      </div>
      <label className="field">
        <span>Channel</span>
        <input
          className="nodrag"
          value={data.channel}
          onChange={(e) => setNodeData(Number(id), { channel: e.target.value })}
          onBlur={() => runNode(Number(id))}
          placeholder="shared-component"
        />
      </label>
      <button className="btn-node primary small f-run nodrag" onClick={() => runNode(Number(id))}>
        {data.mode === "send" ? "Передать" : "Получить"}
      </button>
      <div className="bridge-chip">{hasComponent ? "component ready" : "empty channel"}</div>
      <NodeStatus id={id} />
      <OutPorts type="pagebridge" data={data} />
    </NodeShell>
  );
}
