// frontend/src/nodes/StyleDnaNode.svelte
<script lang="ts">
  import type { NodeProps } from "@xyflow/svelte";
  import { flow } from "../flow/state";
  import type { StyleDnaFlowNode } from "../flow/types";
  import NodeShell from "./NodeShell.svelte";
  import NodeStatus from "./NodeStatus.svelte";
  import InPorts from "./InPorts.svelte";
  import OutPorts from "./OutPorts.svelte";

  let { id, data, selected }: NodeProps<StyleDnaFlowNode> = $props();

  let busy = $derived(!!$flow.busy[Number(id)]);
  let tokensText = $derived(data.tokens ? JSON.stringify(data.tokens, null, 2) : "");
</script>

<NodeShell {id} type="styledna" {selected}>
  <InPorts type="styledna" />
  <div class="ctl-row">
    <button class="btn-node primary small f-run nodrag" disabled={busy} onclick={() => $flow.runNode(Number(id))}>
      {#if busy}<span class="spinner"></span>{/if} Extract DNA
    </button>
  </div>
  {#if data.summary}
    <pre class="dna-summary">{data.summary}</pre>
  {:else}
    <div class="bp-hint">IR или tokens → палитра, шрифты, радиусы, отступы</div>
  {/if}
  {#if tokensText}
    <details class="rs-log f-log">
      <summary>tokens</summary>
      <div class="rs-log-lines">
        <pre>{tokensText.slice(0, 1400)}</pre>
      </div>
    </details>
  {/if}
  <NodeStatus {id} />
  <OutPorts type="styledna" {data} />
</NodeShell>

// frontend/src/nodes/StyleDnaNode.tsx
import type { NodeProps } from "@xyflow/react";
import { useFlowStore } from "../flow/store";
import type { StyleDnaFlowNode } from "../flow/types";
import { NodeShell, NodeStatus } from "./NodeShell";
import { InPorts, OutPorts } from "./PortHandles";

export function StyleDnaNode({ id, data, selected }: NodeProps<StyleDnaFlowNode>) {
  const runNode = useFlowStore((s) => s.runNode);
  const busy = useFlowStore((s) => !!s.busy[Number(id)]);
  const tokensText = data.tokens ? JSON.stringify(data.tokens, null, 2) : "";
  return (
    <NodeShell id={id} type="styledna" selected={selected}>
      <InPorts type="styledna" />
      <div className="ctl-row">
        <button className="btn-node primary small f-run nodrag" disabled={busy} onClick={() => runNode(Number(id))}>
          {busy ? <span className="spinner" /> : null} Extract DNA
        </button>
      </div>
      {data.summary ? <pre className="dna-summary">{data.summary}</pre> : <div className="bp-hint">IR или tokens → палитра, шрифты, радиусы, отступы</div>}
      {tokensText ? (
        <details className="rs-log f-log">
          <summary>tokens</summary>
          <div className="rs-log-lines">
            <pre>{tokensText.slice(0, 1400)}</pre>
          </div>
        </details>
      ) : null}
      <NodeStatus id={id} />
      <OutPorts type="styledna" data={data} />
    </NodeShell>
  );
}
