// frontend/src/editor/CanvasStage.tsx
/* Канвас DNA-редактора: линейки, рейка инструментов, .fe-canvas-inner — хост
 * IRRenderer + GeoEdit (императивные движки). Pan/wheel-zoom навешиваются один раз
 * нативными слушателями (wheel нужен non-passive), логика — в контроллере. */
import { useEffect } from "react";
import * as ctl from "./controller";
import { ToolRail } from "./ToolRail";

export function CanvasStage() {
  useEffect(() => {
    const canvas = ctl.dom.canvas;
    if (!canvas) return;
    const onDown = (e: PointerEvent) => ctl.onCanvasPointerDown(e);
    const onWheel = (e: WheelEvent) => ctl.onCanvasWheel(e);
    canvas.addEventListener("pointerdown", onDown);
    canvas.addEventListener("wheel", onWheel, { passive: false });
    // линейки перерисовываем и при ресайзе окна
    const onResize = () => ctl.drawRulers();
    window.addEventListener("resize", onResize);
    return () => {
      canvas.removeEventListener("pointerdown", onDown);
      canvas.removeEventListener("wheel", onWheel);
      window.removeEventListener("resize", onResize);
    };
  }, []);

  return (
    <div className="fe-canvas" ref={(el) => { ctl.dom.canvas = el; }}>
      <div className="fe-ruler-corner"></div>
      <div className="fe-ruler-h"><canvas ref={(el) => { ctl.dom.rulerH = el; }}></canvas></div>
      <div className="fe-ruler-v"><canvas ref={(el) => { ctl.dom.rulerV = el; }}></canvas></div>
      <ToolRail />
      <div className="fe-canvas-inner" ref={(el) => { ctl.dom.canvasInner = el; }}></div>
    </div>
  );
}

// frontend/src/editor/CanvasStage.svelte
<script lang="ts">
  /* Канвас DNA-редактора: линейки, рейка инструментов, .fe-canvas-inner — хост
   * IRRenderer + GeoEdit (императивные движки). Pan/wheel-zoom навешиваются один раз
   * нативными слушателями (wheel нужен non-passive), логика — в контроллере. */
  import * as ctl from "./controller";
  import ToolRail from "./ToolRail.svelte";

  let canvas: HTMLDivElement | null = $state(null);
  let canvasInner: HTMLDivElement | null = $state(null);
  let rulerH: HTMLCanvasElement | null = $state(null);
  let rulerV: HTMLCanvasElement | null = $state(null);

  $effect(() => {
    ctl.dom.canvas = canvas;
    ctl.dom.canvasInner = canvasInner;
    ctl.dom.rulerH = rulerH;
    ctl.dom.rulerV = rulerV;
  });

  $effect(() => {
    const el = canvas;
    if (!el) return;
    const onDown = (e: PointerEvent) => ctl.onCanvasPointerDown(e);
    const onWheel = (e: WheelEvent) => ctl.onCanvasWheel(e);
    el.addEventListener("pointerdown", onDown);
    el.addEventListener("wheel", onWheel, { passive: false });
    const onResize = () => ctl.drawRulers();
    window.addEventListener("resize", onResize);
    return () => {
      el.removeEventListener("pointerdown", onDown);
      el.removeEventListener("wheel", onWheel);
      window.removeEventListener("resize", onResize);
    };
  });
</script>

<div class="fe-canvas" bind:this={canvas}>
  <div class="fe-ruler-corner"></div>
  <div class="fe-ruler-h"><canvas bind:this={rulerH}></canvas></div>
  <div class="fe-ruler-v"><canvas bind:this={rulerV}></canvas></div>
  <ToolRail />
  <div class="fe-canvas-inner" bind:this={canvasInner}></div>
</div>
