// frontend/src/editor/InspectorPanel.svelte
<script lang="ts">
  /* Правая панель инспектора — чистый Svelte (без window.Inspector/innerHTML).
   * Контроллер хранит сессию (sel/ir/viewport/geo) и бампит store.inspectorTick;
   * панель перечитывает сессию и перемонтирует дерево по key={tick} — как legacy
   * перестраивал innerHTML. События — нативные, навешивает wireInspector после
   * монтирования (инпуты неконтролируемые: коммит по change, как в editor.js). */
  import * as ctl from "./controller";
  import { editorUi } from "./state";
  import SharedInspector from "./inspector/SharedInspector.svelte";
  import { wireInspector } from "./inspector/wireInspector";
  import { tick as afterDomUpdate } from "svelte";

  const tick = $derived($editorUi.inspectorTick);

  const sess = $derived.by(() => {
    void $editorUi.inspectorTick;
    return ctl.getSession();
  });
  const selCount = $derived(sess ? sess.sel.length : 0);
  const source = $derived(selCount ? ctl.sourceForSelection() : null);
  let contentRoot = $state<HTMLDivElement | null>(null);
  const wiredRoots = new WeakSet<HTMLDivElement>();

  $effect(() => {
    const version = tick;
    const node = contentRoot;
    if (!node) return;
    void afterDomUpdate().then(() => {
      requestAnimationFrame(() => {
        if (
          contentRoot === node &&
          tick === version &&
          node.isConnected &&
          !wiredRoots.has(node)
        ) {
          wiredRoots.add(node);
          wireInspector(node);
        }
      });
    });
  });
</script>

<div class="fe-inspector">
  {#if selCount}
    {#key tick}
      <div bind:this={contentRoot}>
        {#if source}
          <div class="fe-source-origin" style="--source-color: {source.color}">
            <span class="fe-source-origin-symbol">{source.symbol || "S"}</span>
            <span><b>{source.label}</b><small>{source.kind || "source"} · {Math.round((source.confidence ?? 1) * 100)}%</small></span>
            <span class="fe-source-origin-state">linked</span>
          </div>
        {/if}
        <div class="fe-shared-insp">
          <SharedInspector />
        </div>
      </div>
    {/key}
  {:else}
    <div class="fe-insp-empty"><span>✦</span><strong>Выберите объект</strong><p>Нажмите элемент на холсте или в слоях. Затем опишите AI, что изменить.</p></div>
  {/if}
</div>

// frontend/src/editor/InspectorPanel.tsx
/* Правая панель инспектора — чистый React (фаза A2, без window.Inspector/innerHTML).
 * Контроллер хранит сессию (sel/ir/viewport/geo) и бампит store.inspectorTick;
 * панель перечитывает сессию и перемонтирует дерево по key={tick} — как legacy
 * перестраивал innerHTML. События — нативные, навешивает wireInspector после
 * монтирования (инпуты неконтролируемые: коммит по change, как в editor.js). */
import { useEffect, useRef } from "react";
import type { CSSProperties } from "react";
import * as ctl from "./controller";
import { useEditorStore } from "./store";
import { SharedInspector } from "./inspector/SharedInspector";
import { TypeGroups } from "./inspector/TypeGroups";
import { wireInspector } from "./inspector/wireInspector";

export function InspectorPanel() {
  const tick = useEditorStore((s) => s.inspectorTick);
  const contentRef = useRef<HTMLDivElement>(null);
  const wiredRef = useRef<HTMLDivElement | null>(null);

  const sess = ctl.getSession();
  const selCount = sess ? sess.sel.length : 0;
  const source = selCount ? ctl.sourceForSelection() : null;

  // проводка событий — один раз на свежесмонтированное дерево (key={tick})
  useEffect(() => {
    const content = contentRef.current;
    if (!content || wiredRef.current === content) return;
    wiredRef.current = content;
    wireInspector(content);
  });

  return (
    <div className="fe-inspector">
      {selCount ? (
        <div key={tick} ref={contentRef}>
          {source ? (
            <div className="fe-source-origin" style={{ "--source-color": source.color } as CSSProperties}>
              <span className="fe-source-origin-symbol">{source.symbol || "S"}</span>
              <span><b>{source.label}</b><small>{source.kind || "source"} · {Math.round((source.confidence ?? 1) * 100)}%</small></span>
              <span className="fe-source-origin-state">linked</span>
            </div>
          ) : null}
          <div className="fe-shared-insp">
            <SharedInspector />
          </div>
          {selCount === 1 ? <TypeGroups /> : null}
        </div>
      ) : (
        <div className="fe-insp-empty">Выделите элемент на канвасе или в слоях</div>
      )}
    </div>
  );
}
