// frontend/src/editor/LayersPanel.svelte
<script lang="ts">
  /* Панель слоёв: поиск (Svelte) + дерево слоёв (императивный остров контроллера —
   * строки, drag-reorder, hide/lock-флаги строятся портом renderLayers из editor.js). */
  import * as ctl from "./controller";

  let search: HTMLInputElement | null = $state(null);
  let layersTree: HTMLDivElement | null = $state(null);

  $effect(() => {
    ctl.dom.search = search;
    ctl.dom.layersTree = layersTree;
  });
</script>

<div class="fe-layers">
  <div class="fe-layers-head">Слои</div>
  <input
    class="fe-search"
    placeholder="Поиск слоёв…"
    bind:this={search}
    oninput={(e) => ctl.setLayerQuery(e.currentTarget.value)}
  />
  <div class="fe-layers-tree" bind:this={layersTree}></div>
</div>

// frontend/src/editor/LayersPanel.tsx
/* Панель слоёв: поиск (React) + дерево слоёв (императивный остров контроллера —
 * строки, drag-reorder, hide/lock-флаги строятся портом renderLayers из editor.js). */
import * as ctl from "./controller";

export function LayersPanel() {
  return (
    <div className="fe-layers">
      <div className="fe-layers-head">Слои</div>
      <input
        className="fe-search"
        placeholder="Поиск слоёв…"
        ref={(el) => { ctl.dom.search = el; }}
        onChange={(e) => ctl.setLayerQuery(e.target.value)}
      />
      <div className="fe-layers-tree" ref={(el) => { ctl.dom.layersTree = el; }} />
    </div>
  );
}
