// frontend/src/editor/TopBar.tsx
/* Верхний тулбар DNA-редактора: зум, вьюпорты, выравнивание, история, Style DNA,
 * закрыть/сохранить. Разметка 1:1 из legacy editor.js (data-act — контракт тестов).
 * Динамика (zoom-текст, hidden-группы, disabled undo/redo) — императивно через dom-refs
 * контроллера, React эти атрибуты не трогает. */
import * as ctl from "./controller";

export function TopBar() {
  return (
    <div className="fe-toolbar">
      <span className="fe-logo">✦ DNA Editor</span>
      <button className="fe-tbtn" data-act="zoom-out" title="Уменьшить" onClick={() => ctl.handleAct("zoom-out")}>−</button>
      <span className="fe-zoom" ref={(el) => { dom_zoom(el); }}>100%</span>
      <button className="fe-tbtn" data-act="zoom-in" title="Увеличить" onClick={() => ctl.handleAct("zoom-in")}>+</button>
      <button className="fe-tbtn" data-act="zoom-fit" title="Вписать" onClick={() => ctl.handleAct("zoom-fit")}>⊡</button>
      <span className="fe-sep"></span>
      <span className="fe-viewports" hidden ref={(el) => { ctl.dom.viewports = el; }}>
        <button className="fe-tbtn active" data-viewport="desktop" title="Desktop 1440 px" onClick={() => ctl.setViewport("desktop")}>D</button>
        <button className="fe-tbtn" data-viewport="tablet" title="Tablet 768 px" onClick={() => ctl.setViewport("tablet")}>T</button>
        <button className="fe-tbtn" data-viewport="mobile" title="Mobile 390 px" onClick={() => ctl.setViewport("mobile")}>M</button>
        <input
          className="fe-viewport-width" type="number" min={320} max={2560} step={1} defaultValue={1440}
          title="Custom canvas width"
          ref={(el) => { ctl.dom.viewportWidth = el; }}
          onChange={(e) => ctl.setPreviewWidth(e.target.value)}
        />
      </span>
      <span className="fe-sep fe-responsive-sep" hidden ref={(el) => { ctl.dom.responsiveSep = el; }}></span>
      <span className="fe-align-group" hidden ref={(el) => { ctl.dom.alignGroup = el; }}>
        <button className="fe-tbtn" data-act="align-left" title="По левому краю" onClick={() => ctl.handleAct("align-left")}>⫷</button>
        <button className="fe-tbtn" data-act="align-center-h" title="По центру по горизонтали" onClick={() => ctl.handleAct("align-center-h")}>⫿</button>
        <button className="fe-tbtn" data-act="align-right" title="По правому краю" onClick={() => ctl.handleAct("align-right")}>⫸</button>
        <span className="fe-sep"></span>
        <button className="fe-tbtn" data-act="align-top" title="По верхнему краю" onClick={() => ctl.handleAct("align-top")}>⊤</button>
        <button className="fe-tbtn" data-act="align-center-v" title="По центру по вертикали" onClick={() => ctl.handleAct("align-center-v")}>⊶</button>
        <button className="fe-tbtn" data-act="align-bottom" title="По нижнему краю" onClick={() => ctl.handleAct("align-bottom")}>⊥</button>
        <span className="fe-sep"></span>
        <button className="fe-tbtn" data-act="distribute-h" title="Распределить по горизонтали" onClick={() => ctl.handleAct("distribute-h")}>↔</button>
        <button className="fe-tbtn" data-act="distribute-v" title="Распределить по вертикали" onClick={() => ctl.handleAct("distribute-v")}>↕</button>
        <span className="fe-sep"></span>
      </span>
      <button className="fe-tbtn" data-act="forward" title="Выше (])" onClick={() => ctl.handleAct("forward")}>⇈</button>
      <button className="fe-tbtn" data-act="backward" title="Ниже ([)" onClick={() => ctl.handleAct("backward")}>⇊</button>
      <button className="fe-tbtn" data-act="group" title="Группа (Ctrl+G)" onClick={() => ctl.handleAct("group")}>⧉</button>
      <button className="fe-tbtn" data-act="ungroup" title="Разгруппировать (Ctrl+Shift+G)" onClick={() => ctl.handleAct("ungroup")}>⧠</button>
      <button className="fe-tbtn" data-act="undo" title="Отменить (Ctrl+Z)" ref={(el) => { ctl.dom.undoBtn = el; }} onClick={() => ctl.handleAct("undo")}>↩</button>
      <button className="fe-tbtn" data-act="redo" title="Повторить (Ctrl+Shift+Z)" ref={(el) => { ctl.dom.redoBtn = el; }} onClick={() => ctl.handleAct("redo")}>↪</button>
      <button className="fe-tbtn" data-act="style-dna" title="Style DNA" onClick={() => ctl.handleAct("style-dna")}>🧬</button>
      <span className="fe-spacer"></span>
      <button className="fe-btn danger" data-act="close" onClick={() => ctl.handleAct("close")}>Закрыть</button>
      <button className="fe-btn primary" data-act="save" onClick={() => ctl.handleAct("save")}>💾 Сохранить</button>
    </div>
  );
}

function dom_zoom(el: HTMLSpanElement | null) {
  ctl.dom.zoomLabel = el;
}

// frontend/src/editor/TopBar.svelte
<script lang="ts">
  /* Верхний тулбар DNA-редактора: зум, вьюпорты, выравнивание, история, Style DNA,
   * закрыть/сохранить. Разметка 1:1 из legacy editor.js (data-act — контракт тестов).
   * Динамика (zoom-текст, hidden-группы, disabled undo/redo) — императивно через dom-refs
   * контроллера, Svelte эти атрибуты не трогает. */
  import * as ctl from "./controller";

  let zoomLabel: HTMLSpanElement | null = $state(null);
  let viewports: HTMLSpanElement | null = $state(null);
  let viewportWidth: HTMLInputElement | null = $state(null);
  let responsiveSep: HTMLSpanElement | null = $state(null);

  $effect(() => {
    ctl.dom.zoomLabel = zoomLabel;
    ctl.dom.viewports = viewports;
    ctl.dom.viewportWidth = viewportWidth;
    ctl.dom.responsiveSep = responsiveSep;
    ctl.syncToolbarState();
  });
</script>

<div class="fe-toolbar">
  <span class="fe-logo">✦ DNA Editor</span>
  <button class="fe-tbtn" data-act="zoom-out" title="Уменьшить" onclick={() => ctl.handleAct("zoom-out")}>−</button>
  <span class="fe-zoom" bind:this={zoomLabel}>100%</span>
  <button class="fe-tbtn" data-act="zoom-in" title="Увеличить" onclick={() => ctl.handleAct("zoom-in")}>+</button>
  <button class="fe-tbtn" data-act="zoom-fit" title="Вписать" onclick={() => ctl.handleAct("zoom-fit")}>⊡</button>
  <span class="fe-sep"></span>
  <span class="fe-viewports" hidden bind:this={viewports}>
    <button class="fe-tbtn fe-viewport-btn active" data-viewport="desktop" title="Desktop 1440 px" onclick={() => ctl.setViewport("desktop")}>
      <svg class="fe-device-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="13" rx="2"></rect><path d="M8 21h8M12 17v4"></path></svg>
      <span>Desktop</span>
    </button>
    <button class="fe-tbtn fe-viewport-btn" data-viewport="tablet" title="Tablet 768 px" onclick={() => ctl.setViewport("tablet")}>
      <svg class="fe-device-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="2" width="14" height="20" rx="2"></rect><path d="M10 18h4"></path></svg>
      <span>Tablet</span>
    </button>
    <button class="fe-tbtn fe-viewport-btn" data-viewport="mobile" title="Mobile 390 px" onclick={() => ctl.setViewport("mobile")}>
      <svg class="fe-device-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="7" y="2" width="10" height="20" rx="2"></rect><path d="M10 18h4"></path></svg>
      <span>Mobile</span>
    </button>
    <input
      class="fe-viewport-width"
      type="number"
      min={320}
      max={2560}
      step={1}
      value={1440}
      title="Custom canvas width"
      bind:this={viewportWidth}
      oninput={(e) => ctl.setPreviewWidth(e.currentTarget.value)}
    />
  </span>
  <span class="fe-sep fe-responsive-sep" hidden bind:this={responsiveSep}></span>
  <span class="fe-spacer"></span>
  <button class="fe-btn danger" data-act="close" onclick={() => ctl.handleAct("close")}>Закрыть</button>
  <button class="fe-btn primary" data-act="save" onclick={() => ctl.handleAct("save")}>💾 Сохранить</button>
</div>
